# Generated by Django 2.2.7 on 2019-11-12 10:52

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='流程名称')),
            ],
            options={
                'verbose_name': '流程名称',
                'verbose_name_plural': '流程名称',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=30, verbose_name='步骤名称')),
                ('step_detail', mdeditor.fields.MDTextField(verbose_name='步骤说明')),
                ('flow_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicize.FlowPath', verbose_name='流程名称')),
            ],
            options={
                'verbose_name': '步骤',
                'verbose_name_plural': '步骤',
            },
        ),
    ]
